name: Publish

on:
  push:
    branches:
    - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Requirements
      run: |
        pip3 install -r requirements.txt
    - name: Sphinx build
      run: |
        sphinx-multiversion . build
    - name: Publish gh-pages
      run: |
        cd build
        git init
        git config user.name "FCCSW Bot"
        git config user.email "fccsw.bot@example.com"
        git remote add upstream https://kjvbrt:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

        touch .nojekyll
        git add .nojekyll
        git commit -m "Initial commit"
        git branch -m gh-pages
        touch .
        cp ../.github/aux/gh-pages-redirect.html index.html
        git add -A .
        git commit -m "Rebuild page at ${GITHUB_SHA}"
        git push -f upstream gh-pages:gh-pages
